input_shape: [128, 1]
conv_layers:
  - filters: 32
    kernel_size: 3
    activation: relu
  - filters: 64
    kernel_size: 3
    activation: relu
dense_units: 64
epochs: 10
batch_size: 32
learning_rate: 0.001
